services:
  - type: web
    name: black-hole-ai
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GIGACHAT_AUTH_KEY
        sync: false
